// <auto-generated />
using System;
using GlucoControl.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GlucoControl.Repository.Migrations
{
    [DbContext(typeof(GlucoControlDbContext))]
    [Migration("20200902185308_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GlucoControl.Repository.Models.Control", b =>
                {
                    b.Property<Guid>("ControlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ControlDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GlucoseLevel")
                        .HasColumnType("int");

                    b.Property<int?>("InsulinAmount")
                        .HasColumnType("int");

                    b.Property<Guid?>("InsulinId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("ProvideInsulin")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ControlId");

                    b.HasIndex("InsulinId");

                    b.HasIndex("UserId");

                    b.ToTable("Controls");
                });

            modelBuilder.Entity("GlucoControl.Repository.Models.Insulin", b =>
                {
                    b.Property<Guid>("InsulinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GenericName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("InsulinTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Peak")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartTime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InsulinId");

                    b.HasIndex("InsulinTypeId");

                    b.ToTable("Insulins");
                });

            modelBuilder.Entity("GlucoControl.Repository.Models.InsulinType", b =>
                {
                    b.Property<Guid>("InsulinTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InsulinTypeId");

                    b.ToTable("InsulinTypes");
                });

            modelBuilder.Entity("GlucoControl.Repository.Models.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("GlucoControl.Repository.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Lastname1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GlucoControl.Repository.Models.Control", b =>
                {
                    b.HasOne("GlucoControl.Repository.Models.Insulin", "Insulin")
                        .WithMany()
                        .HasForeignKey("InsulinId");

                    b.HasOne("GlucoControl.Repository.Models.User", "User")
                        .WithMany("Control")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GlucoControl.Repository.Models.Insulin", b =>
                {
                    b.HasOne("GlucoControl.Repository.Models.InsulinType", "InsulinType")
                        .WithMany("Insulin")
                        .HasForeignKey("InsulinTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GlucoControl.Repository.Models.User", b =>
                {
                    b.HasOne("GlucoControl.Repository.Models.Role", "Role")
                        .WithMany("User")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
