//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlucoControl.Repository.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Control
    {
        public System.Guid ControlId { get; set; }
        public System.DateTime ControlDate { get; set; }
        public int GlucoseLevel { get; set; }
        public Nullable<bool> ProvideInsulin { get; set; }
        public Nullable<System.Guid> InsulinId { get; set; }
        public Nullable<int> InsulinAmount { get; set; }
        public System.Guid UserId { get; set; }
    
        public virtual Insulin Insulin { get; set; }
        public virtual User User { get; set; }
    }
}
